#--------- Start prometheus veeam exporter  ---------#
  - job_name: "veeam"
    metrics_path: /metrics
    file_sd_configs:
      - files: [ "/etc/prometheus/veeam_nodes/*.yml" ]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      # use the value set in __tmp_source_host as exporter host name
      - source_labels: [__tmp_exporter_host]
        target_label: __address__
      # or directly:
      # - target_label: __address__
      #   replacement: "veeam_exporter_host.domain.name:9247"  # The veeam exporter's real hostname.

#--------- End prometheus veeam exporter ---------#
